-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg/w3HXsFA9SUvc7F8
SG4BX3CCRQfOGBqfmCaiqUrnQVugCgYIKoZIzj0DAQehRANCAAQqDJSKJm34CsST
oEqAlNODtS46MqtYi7VIgKrE8/m91Hjqfx2tqlSPs6ZqYZX0eAA4HDmnoDri/ALx
dgqoYPXL
-----END PRIVATE KEY-----